name: Build Chaser

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Build Solution
      run: msbuild Builds/VisualStudio2013/Chaser.sln /p:Configuration=Release /p:Platform=x64

    - uses: actions/upload-artifact@v4
      with:
        name: Chaser-Build
        path: |
          Builds/VisualStudio2013/x64/Release/*.dll
          Builds/VisualStudio2013/x64/Release/*.exe
