name: Build Chaser

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Chaser
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build Solution
      run: msbuild Chaser.sln /p:Configuration=Release

    - name: Upload Binaries
      uses: actions/upload-artifact@v4
      with:
        name: Chaser-Build
        path: |
          Builds/VisualStudio*/x64/Release/*.dll
          Builds/VisualStudio*/x64/Release/*.exe
