name: Build Chaser

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Find MSBuild Path
      id: vs
      run: |
        echo "##[group]Finding Visual Studio installation path"
        vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        echo "##[endgroup]"
        VS_PATH=$(vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath)
        echo "MSBUILD_PATH=$VS_PATH/MSBuild/Current/Bin/MSBuild.exe" >> $GITHUB_OUTPUT

    - name: Build Solution
      run: '"${{ steps.vs.outputs.MSBUILD_PATH }}" Builds/VisualStudio2013/Chaser.sln /p:Configuration=Release /p:Platform=x64'

    - uses: actions/upload-artifact@v4
      with:
        name: Chaser-Build
        path: |
          Builds/VisualStudio2013/x64/Release/*.dll
          Builds/VisualStudio2013/x64/Release/*.exe
