name: Build Chaser

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Find MSBuild Path
      id: vs
      shell: pwsh
      run: |
        Write-Host "##[group]Finding Visual Studio installation path"
        $vsPath = & vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        Write-Host "##[endgroup]"
        "MSBUILD_PATH=$vsPath/MSBuild/Current/Bin/MSBuild.exe" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Build Solution
      shell: pwsh
      run: |
        & "${{ steps.vs.outputs.MSBUILD_PATH }}" "Builds/VisualStudio2013/Chaser.sln" /p:Configuration=Release /p:Platform=x64

    - uses: actions/upload-artifact@v4
      with:
        name: Chaser-Build
        path: |
          Builds/VisualStudio2013/x64/Release/*.dll
          Builds/VisualStudio2013/x64/Release/*.exe
